<?php

namespace AppBundle\Repository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastComments($limit)
    {
        return $this->createQueryBuilder('c')
            ->select('c, post')
            ->leftJoin('c.post', 'post')
            ->setMaxResults($limit)
            ->orderBy('c.id', 'DESC')
            ->getQuery()
            ->getResult()
            ;
    }
}
