# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    app.testSent: Some sentence from setter

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.test:
        class: AppBundle\Services\ServiceManager
        calls:
            - [setEny, ['%app.testSent%']]